[package]
name = "monkeyword-windows"
version = "0.1.0"
description = "monkeyword Windows desktop app"
authors = ["ZINE Inc."]
license = "MIT"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-store = "2"
thiserror = "2"
